In [ ]:
import pandas as pd
sal = pd.read_csv("C:\\Users\\Shruti\\Downloads\\Salaries.csv\\Salaries.csv")
#have to convert because dtype is object for basepay so we have to cleanit
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce')
sal = sal.dropna(subset=['BasePay'])
sal['BasePay'].mean()

C:\Users\Shruti\AppData\Local\Temp\ipykernel_32212\1770223978.py:2: DtypeWarning: Columns (0: BasePay, 1: OvertimePay, 2: OtherPay, 3: Benefits, 4: Status) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.read_csv("C:\\Users\\Shruti\\Downloads\\Salaries.csv\\Salaries.csv")

np.float64(66325.44884048769)

In [8]:
sal['BasePay'].isnull().sum()

np.int64(0)

In [9]:
#job title of joseph driscoll
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

In [10]:
# how much joseph driscoll make including benefits
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [11]:
# name of highest paid person including benefits
sal[sal['TotalPayBenefits']== sal['TotalPayBenefits'].max()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

In [12]:
# alternate emthod to get name of highest paid person including benef
sal.loc[sal['TotalPayBenefits'].idxmax()]

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

In [13]:
# name of lowest paid person
sal[sal['TotalPayBenefits']== sal['TotalPayBenefits'].min()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

In [ ]:
#alternate to get lowest paid name
sal.loc[sal['TotalPayBenefits'].idxmax()]['EmployeeName']

'NATHANIEL FORD'

In [17]:
#mean basepay from 2011-14
sal.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [18]:
#unique job title
sal['JobTitle'].nunique()

2154

In [19]:
#top 5 comman jobs
sal['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                6975
Special Nurse                   4382
Registered Nurse                3725
Public Svc Aide-Public Works    2514
Police Officer 3                2411
Name: count, dtype: int64

In [21]:
#job titles with one occurence in 2013
sum(sal[sal['Year']==2013]['JobTitle'].value_counts() == 1)

202

In [26]:
#people having chief in their title
def chief_string(title):
    if 'chief' in title.lower():
        return True
    else:
        return False
sum(sal['JobTitle'].apply(lambda x: chief_string(x)))

624

In [27]:
#relation between length of job title and salary
sal['title_len'] = sal['JobTitle'].apply(len)

In [28]:
sal[['title_len','TotalPayBenefits']].corr()

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036669
TotalPayBenefits  -0.036669          1.000000